### ISSUE TITLE
No color console output when protrator jasmine-spec-reporter is run with Grunt task

### ISSUE THREAD

**Issue by Mletter1** [bcaudan/jasmine-spec-reporter#36] opened 2015-05-18 19:08 UTC
https://stackoverflow.com/questions/29320180/protractor-with-mocha-chai-dont-display-errors-since-1-8-0-migration?newreg=65f63d9e0e184da28a652989872c7d89

Summery of issue described in this stackoverflow thread. I've encountered the same issue running protractor tests through a grunt task where colors will not show up in the output. Running of test with protractor alone has no issues and the colors will display fine.

**Comment by bcaudan** [comment] 2015-05-18 20:45
All right, so if I understand well, you are trying to run protractor with grunt-protractor-runner task. You have configured jasmine-spec-reporter in your protractor conf. When you run protractor alone, colors are displayed but not when you run it with the grunt task.
So, IMHO it does not seem related to jasmine-spec-reporter and I close this issue accordingly.

I use the grunt-protractor-runner task my self and I have no problems with it. Have you correctly set the noColor option?

**Comment by Mletter1** [comment] 2015-05-18 22:20
So, I've currently been trying to track down why its not displaying the colors. The noColor option has been set to false. I can only replicate the color display issue when running protractor with grunt. Currently these are all the version of dependencies I am running. I haven't had time to try older version of jasmine, protractor, ect... At this point I'm now leaning towards there being an issue with grunt or test runner not jasmine-spec-runner. I'll let you know if I find the issue

    "angular-jsdoc": "^0.3.2",
    "archiver": "^0.12.0",
    "generator-env-config": "0.0.2",
    "grunt": "^0.x",
    "grunt-autoprefixer": "^2.2.0",
    "grunt-concurrent": "^0.5.0",
    "grunt-contrib-clean": "^0.5.0",
    "grunt-contrib-concat": "^0.4.0",
    "grunt-contrib-connect": "^0.7.1",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-cssmin": "^0.9.0",
    "grunt-contrib-htmlmin": "^0.3.0",
    "grunt-contrib-imagemin": "^0.9.3",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-contrib-uglify": "^0.4.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-exec": "^0.4.6",
    "grunt-filerev": "^0.2.1",
    "grunt-google-cdn": "^0.4.0",
    "grunt-istanbul": "^0.5.0",
    "grunt-karma": "^0.10.1",
    "grunt-newer": "^0.7.0",
    "grunt-ng-annotate": "^0.4.0",
    "grunt-protractor-coverage": "^0.2.13",
    "grunt-protractor-runner": "^2.x",
    "grunt-protractor-webdriver": "^0.2.0",
    "grunt-replace": "^0.8.0",
    "grunt-svgmin": "^2.0.0",
    "grunt-usemin": "^2.6.2",
    "grunt-war": "^0.4.4",
    "grunt-wiredep": "^2.0.0",
    "install": "^0.1.8",
    "jasmine-core": "^2.2.0",
    "jasmine-reporters": "^2.0.4",
    "jsdoc": "^3.3.0-beta1",
    "jshint-stylish": "^0.2.0",
    "karma": "^0.12.31",
    "karma-coverage": "^0.2.7",
    "karma-jasmine": "^0.3.5",
    "karma-junit-reporter": "^0.2.2",
    "karma-mocha": "~0.1.3",
    "karma-ng-html2js-preprocessor": "^0.1.2",
    "karma-phantomjs-launcher": "^0.1.4",
    "load-grunt-tasks": "^3.0.0",
    "npm": "^2.7.3",
    "protractor": "^2.x",
    "time-grunt": "^0.3.2",
    "webdriver-manager": "^2.0.0",
    "yo": "^1.3.3",
    "jasmine-spec-reporter": "^2.x"

**Comment by deonclem** [comment] 2015-05-26 11:00
I'm running into the same issue, no color output with :
    "grunt-protractor-runner": "^2.0.0",
    "jasmine-core": "^2.3.4",
    "jasmine-spec-reporter": "^2.2.2",
    "protractor": "^2.1.0"
Did you manage to find a workaround @Mletter1 ?

**Comment by Mletter1** [comment] 2015-05-26 15:19
Still haven't found a fix. I've tried older versions of grunt protractor runner and protractor with no luck.

**Comment by pmowrer** [comment] 2015-05-26 20:22
I'm having the same problem after upgrading from protractor/jasmine/jasmine-spec-reporter `2.0`/`2.1.1`/`2.1.0` -> `2.1`/`2.3.1`/`2.2.2`, except I'm not running protractor through grunt protractor runner.

**Comment by bcaudan** [comment] 2015-05-26 20:53
Can you reproduce it by clonining this repository and launching the [protractor example](https://github.com/bcaudan/jasmine-spec-reporter#developement)?

**Comment by pmowrer** [comment] 2015-05-26 21:22
@bcaudan I can't -- the example works! I also tried updating it to skip starting the selenium server and use `directConnect: true`, which is how my environment is set up. Will do some more digging when I get time.

**Comment by pmowrer** [comment] 2015-05-26 21:24
@bcaudan Just a hunch, but it might be due to a difference in how Protractor is launched. I launch it as a node child process and I would imagine that the grunt task does something similar.

**Comment by bcaudan** [comment] 2015-05-29 06:13
This issue is due to the plugin used to color the jasmine-spec-reporter output, if you run jasmine test into a child process with output piped, then colors are not displayed.

So you can have this issue if you use `grunt-protractor-runner` >= 1.2.0 (see [options.output](https://github.com/teerapap/grunt-protractor-runner/commit/61d55aafcf2ad736231b3f666d20ee734d9aa50e#diff-39649ce063d4c44b8a7ec60a361a32afR109))

It is related to https://github.com/Marak/colors.js/issues/127.

**Comment by Mletter1** [comment] 2015-05-29 18:50
Nice that did it! After adding colors.enabled to jasmine-spec-reporter.js all the colors are now displaying. 

var colors = require('colors');
colors.enabled = true;
var SpecMetrics = require('./spec-metrics');
var SpecDisplay = require('./spec-display');
...
...
...

**Comment by bcaudan** [comment] 2015-05-30 07:57
I have added it in v2.2.3.

**Closed by bcaudan** 2015-05-30 07:57 UTC
